### PR TITLE
added Data notebook

### PR DESCRIPTION
**Pull request by cosimoNigro**
@Bultako, @cdeil take a look at the `1_Data.ipynb` and let me know.

### CODE REVIEW

**Comment by cdeil** [comment]
@cosimoNigro - Thanks!

It would be nice to show what the IRFs contain, by calling the `peek` method.
Example: https://docs.gammapy.org/0.9/notebooks/cta_1dc_introduction.html#IRFs
Or course there's not so much to see for the instruments that only contain the IRF for one offset, so you'll only get a nice plot for HESS. But that's kind of a key thing that could be shown / explained here - that the format allows to give IRFs for the whole FOV, or just the target position.

For the maps, suggest to add a link to the `results/maps` folder and say that there one can see counts maps for all instruents (or delete that and show a five-panel plot with all counts maps in this notebook)

For the spectra, I would suggest to not re-script the background estimation, to remove that part. Just refer to the Python scripts, say that this is done in `make.py extract-spectra`. If you want to keep it, the plotting code should be improved to not generate the red warnings, and probably to plot the regions on top of a counts image to be nicer.
The part where you open up `SpectrumObservationList.read("results/spectra/veritas")` and explain that that's the reduced dataset and take a `peek` is nice.

**Comment by cosimoNigro** [comment]
I removed the spectrum extraction and I am showing explictly event lists and IRFs with the peek method of the respective classes. The only class I could read the H.E.S.S. psf is `PSF3` bu the output of `peek()` looks wierd, looks like you have only two bins in energy. Could you take a look please @cdeil?

**Comment by cdeil** [comment]
@cosimoNigro - I think you need to push the new version?

**Comment by cosimoNigro** [comment]
Done, sorry.

**Comment by cdeil** [comment]
The PSF plot is just a bad color scale. You could merge and I can fix this later (I'd have to look myself how to adjust the scale).

If you don't show what the Fermi data or data from other IACTs looks like, I'd at least add a sentence that Fermi is different, and also the other IACTs are different at the DL3 level in the sense that they only give the IRF at one offset, which was chosen to match the source offset.

Otherwise looks good!

**Comment by cosimoNigro** [comment]
I also wrote at the top of the notebook "The novelty of this paper is the implementation of the open data format for all the IACT datasets, we will use the DataStore class of gammapy to examine one of them.". The main focus I think are IACT data. Let me know.

**Comment by cdeil** [comment]
You could just `!ls -1 data/fermi` to show what's in the Fermi data folder, or add a sentence linking to the folder where this is described in the README. I don't think the goal is to get plots / load up all data in this notebook.

**Comment by cosimoNigro** [comment]
Done, I am merging. Further adjustments we do in the master directly.

**Comment by cdeil** [comment]
Thank you!

**Pull request merged**
